# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95a91722f21961b7776b9717afc77d0487f047b8d8f27b79bd793c0c78400eae1485010ba938adb98422e61635ee46543bb1a14c218650efa4fc40669ad00d29

test:
  secret_key_base: 743c68aaba80cb760ef42e0051e4459aeb12a0272030e719406780e71f5e16c0c445416510f388975cdc6cae468efb76f0ee4f225dbfb97bfbe3d47051cfa268

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
